Nikkibeesetti/login
ambi-disc/lactation-android pull request #1
Opened 2017-10-01 20:01 UTC by nikkibeesetti

hi matt, check out what i did

2017-10-02 02:21 UTC, MatthewTPage requested changes
Alright, here's some more detailed feedback. Mostly minor stuff. A couple things that actually do need to be fixed, like the internet permission.

Let me know if you have any questions. :)

This should also get tested with the API before it's pushed, I'll have it running tomorrow hopefully.

2017-10-02 02:21 UTC, MatthewTPage commented on app/build.gradle
> +    compile 'com.squareup.retrofit2:retrofit:2.3.0'
Linebreak before this line, please.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/AccountCreationActivity.java
> +
Remove extra linebreak.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/AccountCreationActivity.java
> +    private EditText username;
We don't really need this, do we? We only have firstName, lastName, email, password, organization - no username. Right?

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/AccountCreationActivity.java
> +        firstname = (EditText) findViewById(R.id.firstname);
1) This variable name should follow lower camel case, so a better variable name would be ```firstName```.
2) Here we run into a weird thing. Typically if we have a variable like "email" or "name", we'd expect this to directly be the value described by the variable name. But this value is kind of encapsulated in another object, and EditText. Thus, an even better variable name would be ```firstNameEditText```. 
3) Typically we try to signify use of member variables (class level variables) somehow. For this, using an example of ```value = 42```, we have two options:
i) ```this.value = 42 // prepend "this." to member variables. While the compiler will auto-figure this out in most cases, in a few weird cases you might actually have a local variable of the same name as the member variable, in which case the variable from the innermost scope will be used.``` 
ii)  ```mValue = 42 // Change the variable "value" to "mValue". "m" stands for "member".```
Option ii might be the easiest to implement / understand, if you're confused. So this would bring the best name for this variable to ```mFirstNameEditText```. Never be afraid to have longer variable names :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/AccountCreationActivity.java
> +        lastname = (EditText) findViewById(R.id.lastname);
What I said for the above variable also applies to this variable, as well as "username", "password", "organization" and "email".

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/AccountCreationActivity.java
> +
Display a toast saying "Unable to connect to server."
https://developer.android.com/guide/topics/ui/notifiers/toasts.html

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +        findViewById(R.id.register_button).setOnClickListener(this );
You have an extra space after ```this```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +        findViewById(R.id.login_button).setOnClickListener(this );
You have an extra space after ```this```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +
Delete the two empty lines at the end of this method.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +    private EditText emailEditText;
You see my comment above complaining about your EditText variables in ```AccountCreationActivity.java```? Those comments apply to these two variables as well. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +                        if (!response.isSuccessful()) {
All of this code in the ```onResponse(...)``` method got a lot bigger than I was expecting. It's probably best to throw this to another method and call it here, instead of having all this code here.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +                        }else {
You need a space before ```else```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +
Display a toast saying "Unable to connect to server."
https://developer.android.com/guide/topics/ui/notifiers/toasts.html

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/LoginActivity.java
> +
Delete all of these empty lines at the bottom of the file. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/AccountRequest.java
> + * Created by nbeesett on 10/1/17.
I've never liked how IntelliJ (what Android Studio is based on) puts these comments at the top of files when you create them. Like, git history will show both who created the file and any relevant edit information. So you can probably just remove this comment.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/AccountRequest.java
> +public class AccountRequest {
A better name is probably ```AccountCreationRequest```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/AccountRequest.java
> +    public String getFirstName() {
You can probably just delete the getters and setters, we don't need them in the request object. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/AccountRequest.java
> +
Delete the blank line pls :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/AccountRequest.java
> +    public String profession;
Why are these two variables at the bottom of the file instead of with the other variables declared at the top?

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPI.java
> + * Created by nbeesett on 10/1/17.
Delete please :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPI.java
> +
Delete these two empty lines, please. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +
Delete extra empty line :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +    private static String APIurl = "http://eclipse.matthewpage.xyz:5000/";
Please name ```apiUrl``` :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +
Delete extra linebreak :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +
We probably don't need this empty line.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +
We probably don't need this empty line.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +    private static LactorAPI lactorAPI;
Please rename this ```lactorApi``` :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/build.gradle
> +
Delete this empty line, please.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/AccountRequest.java
> +
No blank line after class declarations, please. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPI.java
> +
No blank line after class/interface declarations, please. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginRequest.java
> +
No blank line after class declarations, please. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginReturn.java
> +
No blank line after class declarations, please. :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginReturn.java
> + * Created by nbeesett on 10/1/17.
Delete please :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginRequest.java
> + * Created by nbeesett on 10/1/17.
Delete please, it only adds clutter :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> + * Created by nbeesett on 10/1/17.
Delete please, it only adds clutter :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LactorAPIHelper.java
> +
Delete this extra space, please.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginReturn.java
> +    private boolean success;
Change these member variables to public, please :)

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginReturn.java
> +        this.success = success;
You can get rid of the setters and the constructor - we only use the getters.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/AndroidManifest.xml
We need to add a permission here to access the internet.
```<uses-permission android:name="android.permission.INTERNET" />```
We also need to request permission at runtime to handle M+ devices properly, but that's more complicated. Add a todo here saying to handle requesting permissions at runtime.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/java/org/lactor/consultant/api/LoginReturn.java
> +public class LoginReturn {
A better name for this class is probably ```LoginResult```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
We don't really need this parent RelativeLayout encapsulating everything else. Just have the LInearLayout.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +
Delete extra blank line.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    xmlns:tools="http://schemas.android.com/tools"
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    android:background="#009688"
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    tools:context="org.lactor.consultant.AccountCreationActivity">
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    android:paddingBottom="@dimen/activity_vertical_margin"
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    android:paddingLeft="@dimen/activity_horizontal_margin"
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    android:paddingRight="@dimen/activity_horizontal_margin"
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +    android:paddingTop="@dimen/activity_vertical_margin"
Move this attribute to the LinearLayout tag before you delete it.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +        android:layout_gravity="top|bottom|right"
We don't need ```layout_gravity```, ```layout_alignParentStart```, or ```layout_alignParentEnd```

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +        android:paddingTop="100dp"
Delete.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:textColor="#fff"
We can abstract colors to the ```values/colors.xml``` file, and reference it using ```@color/white``` or whatever. If the ```values/colors.xml``` file hasn't been auto-generated yet, let me know and I can walk you through how it works.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:textColor="#fff"
Also, 6 characters to represent colors, please. (```#f0f0f0``` is the literal interpretation of what you wrote, but you probably meant ```#ffffff```).

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +
Delete blank line, please.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:layout_gravity="center"
We don't really need this to be centered, alignLeft is fine.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:layout_width="300dp"
We probably don't need to specify the width absolutely. Just use ```match_parent```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:gravity="center"
Remove, because of the width being set to ```match_parent```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:textColorHint="#fff"
This color can be abstracted to colors.xml as well.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:padding= "10dp"
I don't think padding is the best way to do this. Maybe delete this line and do 16dp ```marginTop```, and see how that looks? The changes I've requested will definitely mess with the margins a bit, we can fine tune this when we meet next if the end result doesn't look right.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +        <EditText
All of the comments I said for the previous EditText apply to every EditText in this file, as well as every EditText in ```activity_login.xml```.

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:textColor="#009688"
Abstract color to ```colors.xml```

2017-10-02 02:21 UTC, MatthewTPage commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:hint="Submit"/>
Abstract string to strings.xml so it can be automatically translated if someone wants to use the app in a language other than English.

2017-10-02 02:21 UTC, MatthewPageCS commented on app/src/main/res/layout/activity_account_creation.xml
> +
Too many blank lines at the end of this file.

2017-10-03 00:38 UTC, MatthewPageCS commented on app/src/main/res/layout/activity_account_creation.xml
> +            android:textColor="#fff"
Oops, I was wrong about the above, ```#fff``` resolves to ```#ffffff```. Still, I'd prefer if we used the full 6 character color codes, please :)

2017-10-03 00:39 UTC, MatthewPageCS commented
As a general comment, Github is really weird. If you're confused about what line of code my comment is talking about, it's the line of code directly above my comment.

I'm not a big fan of GitHub's code review, but setting up a better system (like ReviewBoard) would be massive overkill for this project.

2017-10-03 04:15 UTC, nikkibeesetti commented
okay got it! thanks matt!!

2017-10-15 05:53 UTC, nikkibeesetti commented on app/build.gradle
> +    compile 'com.squareup.retrofit2:retrofit:2.3.0'
fixed

2017-10-17 18:19 UTC, MatthewTPage approved these changes

2017-10-17 18:19 UTC, merged